### ISSUE TITLE
StateMachine used with Doctrine Entities

### ISSUE THREAD

**Issue by sagikazarmark** [yohang/Finite#69]
I would like to use a StateMachine implementation with some of my entities, but it seems a bit weird that the statemachine is not injected into the entity, but the entity is injected into the statemachine (maybe because this is new to me).

Any suggestion how to use this lib with doctrine? There is a doctrine behavior implementation, but I would be happier with a doctrine type instead.

**Comment by yohang** [comment]
Hi,

StateMachine won't be injected in your entities, or more globally, state-controlled objects.

Your graph logic has nothing to do in your entities, which are, essentially, data-carrying objects.

If you really want to inject `StateMachine` into Doctrine object, you can do that with a postLoad lifecycle event, but honestly, don't do this.
