### ISSUE TITLE
[Feature request] Add custom properties for transition

### ISSUE THREAD

**Issue by ksn135** [yohang/Finite#75]
It will be very nice to add custom properties to Transition class with method(s?) to retrieve them all or their values from Transition object. Custom properties ONLY on states is not enough. 
I need to hold many additional information about transitions, used in my buisness-processes.
Custom properties in transition is very good place to store such kind of information.
IMHO, it will be a great additional feature to your bundle and also it helps me a lot in my project.
@yohang What do you think about it ?

**Comment by yohang** [comment]
Closing as two PRs are open : #78, #97.
