### ISSUE TITLE
Notice: Undefined index: guard

### ISSUE THREAD

**Issue by sandermarechal** [yohang/Finite#89]
I am getting `Notice: Undefined index: guard` errors in `yohang/finite/src/Finite/Loader/ArrayLoader.php on line 109`. It appears that `$resolver->setOptional(array('guard'))` does not ensure that the 'guard' key exists in the resolved configuration.

I am using Finite 1.0.3 and Symfony/config 2.7.1

**Comment by tim-massey** [comment]
Was there any solution for this?

**Comment by izambasiron** [comment]
Had the same problem with 1.0.3. It was fixed in pull request #74. I'm using `"yohang/finite": "dev-master"` in composer.json

**Comment by sandermarechal** [comment]
Thanks!
