### ISSUE TITLE
Is this still being maintained? 

### ISSUE THREAD

**Issue by MPiccinato** [yohang/Finite#93]
Would love to see some updates. Any chance of this being maintained or should I just fork?

**Comment by RonRademaker** [comment]
It looks abandoned unfortunately. Would be nice to kick it back to life.

**Comment by RonRademaker** [comment]
I've had contact with the Yohan and he indicates the project is not abandoned but he has no time at the moment to maintain it. It's likely he'll give somebody push access soon.

**Comment by MPiccinato** [comment]
@RonRademaker Thanks for the update!

**Comment by hacfi** [comment]
Sounds promising!

**Comment by yohang** [comment]
Hi,

I have some time this week to release 1.1, but i'm searching 1 or 2 co-maintainers at the same time.
